id: 93473694-53E8-43C2-9259-39F32D177D26
alias: Corridoio Accensione Luci Notturna
trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: input_select.sistema_stato_del_giorno
condition:
  - condition: template
    value_template: >
      {{ states("input_select.sistema_stato_del_giorno") in ["Letto", "Notte"] }}
action:
  - service: light.turn_on
    entity_id: 
      - light.corridoio_notturna