- hosts: hosts
  become: true
  roles:
    - role: initial_bringup
      tags: initial

- hosts: hosts
  vars_files:
    - variables/default.yaml
  roles:
    - role: copy_configuration
      tags: configure
    - role: spin_containers
      tags: run