---
# Manage schedule for air freshner.
#
id: d168f724-b882-47cd-9964-31dc305debba
alias: Soggiorno Freshner Schedule
trigger:
  - platform: time_pattern
    hours: '/3'
condition:
  - condition: template
    value_template: >
      {{ states.sensor.sistema_stato_del_giorno.state not in ["Notte"] }}
action:
  - service: switch.turn_on
    entity_id: switch.soggiorno_profumatore
