id: C80FC0EB-72AC-4EB3-8D8B-BD53E5241B6F
alias: Casa Notifica Movimento Telecamere
trigger:
  - platform: state
    entity_id: 
      - binary_sensor.cortile_viale_presenza
      - binary_sensor.cortile_piazzale_presenza
    to: 'on'
condition:
  - condition: state
    entity_id: 'group.famiglia'
    state: 'not_home'
action:
  - service: script.notifica_movimento_telecamere
    data_template:
      camera: >
        camera.{{ trigger.from_state.entity_id.split(".")[1] | replace("_presenza", "") }}