language: python

python: "3.7"

before_install:
  - mv .stubs/secrets.yaml homeassistant/secrets.yaml

install:
  - pip3 install homeassistant
  - pip3 install -r ci-requirements.txt

jobs:
  include:
    - stage: test
      script: hass -c homeassistant/ --script check_config --info all
