language: python

python:
        - "3.7"

before_install:
        - cp .stubs/secrets.yaml homeassistant/secrets.yaml

install:
        - pip3 install homeassistant

script:
        - hass --script check_config -c homeassistant/ -f

after_success:
        - curl $WEBHOOK_DEPLOY
