language: python

python:
        - "3.7"

before_install:
        - cp .stubs/secrets.yaml homeassistant/secrets.yaml
        - cp provision/inventory.stub provision/inventory
        - cp provision/variables/default.yaml.stub provision/variables/default.yaml

install:
        - pip3 install homeassistant
        - pip3 install ansible

jobs:
        include:
                - script: hass --script check_config -c homeassistant/ -f
                - script: cd provision && ansible-playbook playbook.yaml -i inventory --syntax-check
                - script: cd tasmota && ansible-playbook playbook.yaml -i inventory --syntax-check
after_success:
        - test $TRAVIS_BRANCH = "master" && curl -d "" -X POST $WEBHOOK_DEPLOY
