version: '3'
services:
        homeassistant:
                container_name: home-assistant
                image: homeassistant/home-assistant
                volumes:
                        - ./homeassistant:/config
                        - /etc/localtime:/etc/localtime:ro
                restart: always
                network_mode: host
        mosquitto:
                image: eclipse-mosquitto
                container_name: mosquitto
                ports:
                        - "1883:1883"
                        - "9001:9001"
                volumes:
                        - ./mosquitto/:/mosquitto/config/
                restart: always
        motioneye:
                image: ccrisan/motioneye:master-amd64
                container_name: motioneye
                volumes:
                        - /etc/localtime:/etc/localtime:ro
                        - ./motioneye/etc:/etc/motioneye
                        - ./motioneye/lib:/var/lib/motioneye
                devices:
                        - "/dev/video1:/dev/video1"
                        - "/dev/video2:/dev/video2"
                restart: always
                network_mode: host
        puller:
                image: eliseomartelli/puller
                container_name: puller
                restart: always
                volumes:
                        - ./:/config
        ha_dockermon:
                image: philhawthorne/ha-dockermon
                container_name: ha_dockermon
                restart: always
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock
                        - ./ha_dockermon:/config
                ports:
                        - 8126:8126
        duckdns:
                image: linuxserver/duckdns
                container_name: duckdns
                environment:
                        - TZ=Europe/Rome
                        - SUBDOMAINS=${SUBDOMAIN}
                        - TOKEN=${TOKEN}
                restart: always
        caddy:
                image: abiosoft/caddy
                container_name: caddy
                volumes:
                        - ./caddy/certs/:/etc/caddycerts/
                        - ./caddy/Caddyfile:/etc/Caddyfile
                ports:
                        - "80:80"
                        - "443:443"
                        - "2015:2015"
                environment:
                        - CADDYPATH=/etc/caddycerts/
                        - ACME_AGREE=true
                        - DOMAIN=${DOMAIN}
                restart: always
