---
# Turn on garden lights when it's evening.
#
id: 93473694-53E8-43C2-9259-39F32D177C26
alias: Cortile Accensione Luci Serale
trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: sensor.sistema_stato_del_giorno
condition:
  - condition: template
    value_template: >
      {{ states("sensor.sistema_stato_del_giorno") in ["Sera"] }}
action:
  - service: light.turn_on
    entity_id:
      - light.cortile_frontale
