id: 93473694-53E8-43C2-9259-39F32D177C26
alias: Cortile Accensione Luci Serale
trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: input_select.sistema_stato_del_giorno
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: group.areas_cortile
        state: 'off'
      - condition: template
        value_template: >
          {{ states("input_select.sistema_stato_del_giorno") in ["Sera", "Letto"] }}
action:
  - service: light.turn_on
    entity_id:
      - light.cortile_frontale
