---
# If is not night, turn off lights after 15 minutes.
#
id: 7175DE1A-1C01-4F5D-BF84-A8BC6162EE07
alias: Cortile Spegnimento Luci Temporizzato
trigger:
  - platform: state
    entity_id: group.areas_cortile
    to: 'on'
    for:
      minutes: 15
  - platform: state
    entity_id: sensor.sistema_stato_del_giorno
    to: "Notte"
  - platform: homeassistant
    event: start
condition:
  - condition: template
    value_template: >
      {{ states("sensor.sistema_stato_del_giorno") not in ["Sera", "Letto"] }}
action:
  - service: homeassistant.turn_off
    entity_id: group.areas_cortile
