id: 6491E274-8989-457D-B05B-E6708BB87653
alias: Cortile Accensione Luci Presenza
trigger:
  - platform: state
    entity_id:
      - person.antonella
      - person.antonio
      - person.gioele
      - person.eliseo
    to: 'home'
condition:
  - condition: state
    entity_id: input_select.sistema_stato_del_giorno
    state: 'Notte'
  - condition: template
    value_template: >
      {{ (as_timestamp(now()) - as_timestamp(state_attr('automation.cortile_accensione_luci_presenza','last_triggered'))) > 3600 }}
action:
  - service: homeassistant.turn_on
    entity_id: group.luci_esterne
