alias: Cortile Spegnimento Luci Temporizzato
trigger:
  - platform: state
    entity_id: group.luci_esterne
    to: 'on'
    for:
      minutes: 5
condition:
  - condition: template
    value_template: >
      {{ not states("input_select.stato_del_giorno") in ["Sera", "Letto"] }}
action:
  - service: homeassistant.turn_off
    entity_id: group.luci_esterne
