alias: Cortile Spegnimento Luci Temporizzato Pausa Callback
trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      data: '/cortile_spegnimento_luci_temporizzato_override'
condition:
  - condition: template
    value_template: >
      {{ not states("input_select.stato_del_giorno") in ["Sera", "Letto"] }}
action:
  - service: home_assistant.turn_off
    entity_id: automation.cortile_spegnimento_luci_temporizzato
  - delay: '00:00:01'
  - service: home_assistant.turn_on
    entity_id: automation.cortile_spegnimento_luci_temporizzato
  - service: script.notifica_famiglia
    data_template:
      message: "Perfetto, non le spegnerò."
