alias: Cortile Spegnimento Luci Temporizzato
trigger:
  - platform: state
    entity_id: light.cortile_frontale
    to: 'on'
condition:
  condition: and
  conditions:
    - condition: template
      value_template: !include ../../../jinja_templates/template.orario_con_stagione.yaml
    - condition: state
      entity_id: sun.sun
      state: below_horizon
action:
  - delay: '00:15:00'
  - service: light.turn_off
    entity_id: light.cortile_frontale