alias: Cortile Spegnimento Luci Temporizzato
trigger:
  - platform: state
    entity_id: light.cortile_frontale
    to: 'on'
condition:
  - condition: state
    entity_id: input_select.stato_del_giorno
    state: 'Notte'
action:
  - delay: '00:15:00'
  - service: light.turn_off
    entity_id: light.cortile_frontale