alias: Cortile Accensione Luci Presenza
trigger:
  - platform: state
    entity_id: group.famiglia
    to: 'home'
condition:
  - condition: state
    entity_id: input_select.stato_del_giorno
    state: 'Notte'
action:
  - service: homeassistant.turn_on
    entity_id: group.luci_esterne
