alias: Cortile Spegnimento Luci Temporizzato
trigger:
  - platform: state
    entity_id: group.luci_esterne
    to: 'on'
    for:
      minutes: 15
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: input_select.stato_del_giorno
      state: 'Notte'
    - condition: state
      entity_id: input_select.stato_del_giorno
      state: 'Mattina'
    - condition: state
      entity_id: input_select.stato_del_giorno
      state: 'Pomeriggio'
action:
  - service: homeassistant.turn_off
    entity_id: group.luci_esterne