alias: Cortile Spegnimento Luci Tramonto
trigger:
  - platform: template
    value_template: !include ../../../jinja_templates/template.orario_con_stagione.yaml
action:
  - service: light.turn_off
    entity_id: light.cortile_frontale
