alias: Cortile Spegnimento Luci Temporizzato Pausa
trigger:
  - platform: state
    entity_id: group.luci_esterne
    to: 'on'
condition:
  - condition: template
    value_template: >
      {{ not states("input_select.stato_del_giorno") in ["Sera", "Letto"] }}
action:
  - service: script.notifica_famiglia_interattivo
    data_template:
      message: >
        {{
          [
            "Spegnerò le luci tra 15 minuti, vuoi che non le spenga?",
            "Le luci di fuori si spegneranno tra 15 minuti. Vuoi che non le spenga?"
          ]
          | random
        }}
      inline_keyboard:
        - "Sì, non le spegnere:/cortile_spegnimento_luci_temporizzato_pausa_callback_yes"
