alias: Cortile Spegnimento Luci Temporizzato Pausa Callback
trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      data: "/cortile_spegnimento_luci_temporizzato_pausa_callback_yes"
condition:
  - condition: template
    value_template: >
      {{ not states("input_select.stato_del_giorno") in ["Sera", "Letto"] }}
action:
  - service: script.notifica_famiglia
    data_template:
      message: "Ok, non spegnerò le luci."
  - service: homeassistant.turn_off
    entity_id: automation.cortile_spegnimento_luci_temporizzato
  - delay: "00:00:01"
  - service: homeassistant.turn_on
    entity_id: automation.cortile_spegnimento_luci_temporizzato
 
