alias: Cortile Accensione Luci Sera
trigger:
  - platform: state
    entity_id: input_select.stato_del_giorno
    to: 'Sera'
action:
  - service: homeassistant.turn_on
    entity_id: group.luci_esterne
  - service: script.annuncia
    data_template:
      message: > 
        {{ 
          [
            "Inizia ad essere buio, accendo le luci fuori.",
            "Il sole sta tramontando, accendo le luci.",
            "Arrivederci Sole! Illumino il cortile."
          ] 
          | random
        }}