alias: Cortile Spegnimento Luci Temporizzato
trigger:
  - platform: state
    entity_id: group.luci_esterne
    to: 'on'
    for:
      minutes: 15
condition:
  - condition: template
    value_template: >
      {{
        not is_state("input_select.stato_del_giorno", "Sera") 
        or
        not is_state("input_select.stato_del_giorno", "Letto")
      }}
action:
  - service: homeassistant.turn_off
    entity_id: group.luci_esterne
