alias: Cortile Spegnimento Luci Notte
trigger:
  - platform: state
    entity_id: input_select.stato_del_giorno
    to: 'Notte'
action:
  - service: light.turn_off
    entity_id: light.cortile_frontale
