- hosts: all
  gather_facts: no
  vars:
    tasmota_commands:
      - command: topic
        value: "{{ friendly_name | lower | replace(' ', '_') }}"
      - command: FriendlyName
        value: "{{ friendly_name }}"
  roles:
    - ansible-tasmota

- hosts: locks
  gather_facts: no
  vars:
    tasmota_commands:
      - command: Pulsetime
        value: 1
  roles:
    - ansible-tasmota

- hosts: plugs
  gather_facts: no
  vars:
    tasmota_commands:
      - command: SetOption30
        value: "{{ as_light | default('0', True) }}"
  roles:
    - ansible-tasmota

- hosts: all:!locks
  gather_facts: no
  vars:
    tasmota_commands:
      - command: SetOption19
        value: 1
  roles:
    - ansible-tasmota