alias: Sistema Impostazione Notte
trigger:
  - platform: template
    value_template: !include ../../jinja_templates/template.orario_con_stagione.yaml
action:
  - service: input_select.select_option
    data:
      option: Notte
