# Automazione di sistema.
#
# Spegne le notifiche di notte.

alias: Sistema Impostazione Notifiche
trigger:
  - platform: state
    entity_id: input_select.stato_del_giorno
action:
  - service_template: >
      {% if "Notte" in states.input_select.stato_del_giorno.state %}
        homeassistant.turn_off
      {% else %}
        homeassistant.turn_on
      {% endif %}
    entity_id: group.notifiche