---
id: 1B1FE5A9-B874-489F-AFB8-E95276893D40
alias: Sistema Bring Back Tasmotas
description: Sends a MQTT message to re-discover tasmota devices.
trigger:
  - platform: homeassistant
    event: start
action:
  - delay: '00:00:30'
  - service: mqtt.publish
    data:
      payload: "SetOption19 1; Delay 100; State"
      topic: tasmotas/cmnd/backlog
      retain: true
