---
# Send a notification to our phones with the recycle bin to take outside.
#
id: 6c1d6db3-060b-4233-8745-e68251cff480
alias: Sistema Notifica Rifiuti
trigger:
  - platform: time
    at: '19:30:00'
action:
  - service: notify.notify
    data_template:
      message: >
        Domani bisogna buttare{{ " " }}
        {%- set today = states("sensor.casa_rifiuti_di_domani") %}
        {%- if 'PAPER' in today -%}
            la carta
        {%- elif 'PLASTIC' in today -%}
            il multimateriale
        {%- elif 'DRY' in today -%}
          il secco
        {%- elif 'ORGANIC' in today -%}
          l'umido
        {%- elif 'GLASS' in today -%}
          il vetro
        {% else %}
          niente
        {% endif %}
