id: 6c1d6db3-060b-4233-8745-e68251cff480
alias: Sistema Notifica Rifiuti
trigger:
  - platform: time
    at: '19:30:00'
condition:
  - condition: template
    value_template: >
      {{ states("input_select.sistema_stato_del_giorno") not in ["Notte"] }}
action:
  - service: notify.notify
    data_template:
      message: >
        {% set today = states("sensor.casa_rifiuti_di_domani") %}
        {%- if 'PAPER' in today[0] -%}
            la carta
        {%- endif -%}
        {%- if 'PLASTIC' in today[0] -%}
            il multimateriale
        {%- endif -%}
        {%- if 'DRY' in today[0] -%}
          il secco
        {%- endif -%}
        {%- if 'ORGANIC' in today[0] -%}
          l'umido
        {%- endif -%}
        {%- if 'GLASS' in today[0] -%}
          il vetro
        {% else %}
          niente
        {% endif %}