id: CC67FAD1-B90B-4847-9237-95121F117733
alias: Sistema Notifica Telecamere
trigger:
  - platform: state
    entity_id: 
      - binary_sensor.cortile_viale_presenza
      - binary_sensor.cortile_piazzale_presenza
    to: 'on'
condition:
  - condition: template
    value_template: >
      {{ states("input_select.sistema_stato_del_giorno") not in ["Notte"] }}
action:
  - service: notify.notify
    data_template:
      message: Mi sembra di aver visto del movimento
      data:
        image: http://192.168.0.88:8123{{ state_attr("camera." + (trigger.from_state.entity_id.split(".")[1] | replace("_presenza", "")), "entity_picture") }}