---
# Send a notification with the camera feed when there's motion and we are
# outside.
#
id: CC67FAD1-B90B-4847-9237-95121F117733
alias: Cortile Notifica Viale 
trigger:
  - platform: state
    entity_id:
      - binary_sensor.cortile_viale_motion
    to: 'on'
condition:
  - condition: time
    after: '07:30:00'
    before: '23:00:00'
action:
  - service: notify.notify
    data:
      title: '🚨 C''è qualcuno al cancello!'
      message: 'Tieni premuto per vedere la telecamera'
      data:
        entity_id: camera.cortile_viale
        actions:
          - action: OPEN_GATE_1
            title: "Apri Pedonale"
          - action: URI
            uri: /lovelace/telecamere
            title: "Guarda le altre telecamere"
  - delay:
      minutes: 5
