alias: Sala Modalità Cinema Timer
trigger:
  - platform: state
    entity_id: media_player.sala_chromecast
    from: 'playing'
    for: '00:30:00'
  - platform: state
    entity_id: media_player.sala_chromecast
    to: 'unavailable'
  - platform: state
    entity_id: input_boolean.sala_modalita_cinema
    for: '01:30:00'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.sala_modalita_cinema
