alias: Sala Modalità Cinema Timer
trigger:
  - platform: state
    entity_id: input_boolean.sala_modalita_cinema
    to: 'on'
    for: '1:30:00'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.sala_modalita_cinema
