alias: Sala Modalità Cinema Controllo
trigger:
  - platform: state
    entity_id: group.luci_sala
condition:
  - condition: state
    entity_id: input_boolean.sala_modalita_cinema
    state: 'on'
action:
  - service_template: >
      {% if "on" in trigger.to_state.state %}
        media_player.media_pause
      {% else %}
        media_player.media_play
      {% endif %}
    entity_id: media_player.sala_tv_chromecast

