alias: Sala Modalità Cinema
trigger:
  - platform: state
    entity_id: media_player.chromecast_salotto
condition:
  - condition: state
    entity_id: input_boolean.sala_modalita_cinema
    state: 'on'
action:
  - service_template: >
      {% if "playing" in states.media_player.chromecast_salotto.state %}
        light.turn_off
      {% else %}
        light.turn_on
      {% endif %}
    entity_id: light.sala_grande