---
# Turn on cup heater for the morning.
#
id: 3D666750-268D-4C09-ADB0-75EDC86A5898
alias: Cucina Accensione Scaldatazze
trigger:
  - platform: time
    at: '04:30:00'
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: sensor.sistema_stato_del_giorno
  - platform: state
    entity_id: group.family
condition:
  - condition: or
    conditions:
      - condition: template
        value_template: >
          {{ states("sensor.sistema_stato_del_giorno") not in ["Letto", "Notte"] }}
      - condition: template
        value_template: >
          {{ trigger.platform == "time" }}
  - condition: state
    entity_id: group.family
    state: 'home'
action:
  - service: switch.turn_on
    entity_id: switch.cucina_scaldatazze
