---
# If it's dinner/breakfast/lunch time, turn on kitchen downlights.
#
id: 0d6718e9-4f62-4468-aa7c-b6add5cc2ba9
alias: Cucina Accensione Luci Scolapiatti
trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: sensor.sistema_stato_del_giorno
  - platform: time
    at: '19:00:00'
  - platform: state
    entity_id: group.family
    to: 'home'
condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: sensor.sistema_stato_del_giorno
        state: "Mattina"
      - condition: and
        conditions:
          - condition: state
            entity_id: sensor.sistema_stato_del_giorno
            state: "Pranzo"
          - condition: template
            value_template: >
              {{ states("weather.home") not in ["sunny", "partlycloudy"] }}
action:
  - service: light.turn_on
    entity_id: light.cucina_scolapiatti
