---
# Turn off cup heater.
#
id: 6B25111E-A51A-4547-B77D-B60167FB10C6
alias: Cucina Spegnimento Scaldatazze
trigger:
  - platform: state
    entity_id: sensor.sistema_stato_del_giorno
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: group.family
    to: 'not_home'
    for:
      hours: 1
condition:
  - condition: or
    conditions:
      - condition: template
        value_template: >
          {{ states("sensor.sistema_stato_del_giorno") in ["Letto", "Notte"] }}
      # If no one is at home, turn off the cup heater.
      - condition: template
        value_template: >
          {{ trigger.to_state.domain == "group" }}
action:
  - service: switch.turn_off
    entity_id: switch.cucina_scaldatazze
