alias: Casa Simulazione Presenza
trigger:
  - platform: state
    entity_id: group.famiglia
    to: 'not_home'
  - platform: event
    event_type: casa_simulazione_presenza
  - platform: state
    entity_id: input_select.stato_del_giorno
    to: 'Sera'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.simula_presenza
      state: 'on'
    - condition: state
      entity_id: group.famiglia
      state: 'not_home'
    - condition: template
      value_template: >
        {{ not states("input_select.stato_del_giorno") in ["Notte", "Mattina"] }}
action:
  - service: homeassistant.turn_on
    data_template:
      entity_id: {{ states.group.all_lights.attributes.entity_id | random }}
  - delay: '00:00:{{ (range(3, 10) | random) }}'
  - service: homeassistant.turn_off
    entity_id: group.all_lights
  - delay: '00:{{ (range(10, 30) | random) }}:00'
  - event: casa_simulazione_presenza