alias: Notifica Interruzione Sasi
trigger:
  - platform: state
    entity_id: 
      - sensor.feed_sasi_mozzagrogna
condition:
  - condition: template
    value_template: '{{ states("sensor.feed_sasi_mozzagrogna") != "none" }}'
action:
  - service: script.notifica_famiglia
    data_template:
      urgente: True
      message: >
        Possibile interruzione del servizio idrico.  
        Sasi scrive: {{ states.sensor.feed_sasi.attributes.entries[0].title }}.
        {{ states.sensor.feed_sasi.attributes.entries[0].link }}
  - service: script.annuncia
    data_template:
      bisogna_salutare: True
      message: >
        Oggi potrebbero esserci interruzioni del servizio idrico. 
        Ho inviato il link sui vostri telefoni con i dettagli.