alias: Accensione Luci Tramonto
trigger:
  - platform: sun
    event: sunset
    offset: '-00:30:00'
action:
  - service: light.turn_on
    entity_id: light.cortile_frontale
  - delay: '3:30:00'
  - service: light.turn_off
    entity_id: light.cortile_frontale