alias: Notifica Pubblicità Bloccate
trigger:
  - platform: state
    entity_id: input_select.stato_del_giorno
    to: 'Sera'
action:
  - service: script.notifica_famiglia
    data_template:
      message: >
        {{ 
          [
            "Oggi ho bloccato %a pubblicità %e",
            "Volete sapere quante pubblicità ho bloccato oggi? %e\n%a!",
            "%a pubblicità sono state loccate oggi %e"
          ]
          | random 
          | replace("%a", states("sensor.adguard_dns_queries_blocked")) 
          | replace("%e", ["👍", "✅", "✌", "👀", "🔝"] 
            | random) 
        }} 
