alias: Notifica rifiuti di domani
trigger:
  - platform: time
    at: '19:30:00'
action:
  - service: script.notifica_famiglia
    data_template:
      message: !include ../jinja_templates/template.messaggio_rifiuti.yaml
  - service: script.annuncia
    data_template:
      message: !include ../jinja_templates/template.messaggio_rifiuti.yaml