alias: Notifica Movimento Telecamere
trigger:
  - platform: state
    entity_id: 
      - binary_sensor.presenza_viale
    to: 'on'
action:
  - service: script.notifica_famiglia_cctv
    data_template:
      camera: >
        {{ trigger.from_state.entity_id.split(".")[1] | replace("presenza_", "camera.") }}