alias: Accensione Luci Ritorno
trigger:
  - platform: state
    entity_id: group.famiglia
    to: 'home'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: light.cortile_frontale
      state: 'off'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
action:
  - service: light.turn_on
    entity_id: light.cortile_frontale
  - delay: '00:15:00'
  - service: light.turn_off
    entity_id: light.cortile_frontale
