alias: Notifica rifiuti di domani
trigger:
  - platform: time
    at: '19:30:00'
action:
  - service: script.notifica_famiglia
    data_template:
      message: >
        Domani
        {%- if 'niente' in states('sensor.rifiuti_di_domani') -%}
          {{ [' non bisogna buttare niente.',
              ' la munnezza non passa.',
              ' senza bidone (non passa nessuno.)',
              ' EcoLan riposa',
              ' niente spazzatura.'] | random }}
        {%- else -%}
          {{ [' bisogna buttare ',
              ' si caccia ',
              ' passa ',
              ' EcoLan viene a prendersi '] | random }}
          {{- states('sensor.rifiuti_di_domani') -}}
        {%- endif -%}
        
