---
name: Generate Readme
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 */6 * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Build README
        run: .docs/generate_readme.sh .

      - name: Check for changes
        run: |
          ! git diff --quiet

      - name: Commit changes if required
        if: ${{ success() }}
        run: |
          git config --global user.email "readme@eliseomartelli.it"
          git config --global user.name "Readme Bot"
          git add readme.md
          git commit -m 'docs: update readme' || exit 0
          git push
